name: riverpod_movie
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod:
  riverpod_generator:
  riverpod_annotation:

  dio:

  flutter_svg:
  freezed_annotation:
  freezed:
  json_annotation:
  dartz:
  flutter_screenutil:
  equatable:
  logger: 2.0.2+1
  go_router:
  shimmer:
  cached_network_image:
  shared_preferences:
  firebase_core:
  firebase_remote_config:
  isar:
  path_provider:
  isar_flutter_libs:
  get_it:
  injectable_generator:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner:
  json_serializable:
  auto_route_generator:
  isar_generator:

flutter:
  uses-material-design: true

  assets:
    - assets/images/movies/
    - assets/images/icons/

  fonts:
    - family: MerriWeather
      fonts:
        - asset: fonts/merri_weather/Merriweather-Black.ttf
        - asset: fonts/merri_weather/Merriweather-Bold.ttf
    - family: Mulish
      fonts:
        - asset: fonts/mulish/Mulish-Bold.ttf
        - asset: fonts/mulish/Mulish-Regular.ttf
